// api/agents/anna.js — Order-Anna
//
// Triggered by the Stripe webhook `checkout.session.completed`. Writes a row
// to `dpn_orders`, then schedules three customer emails in the Jenifer voice:
//
//   1. ORDER-RECEIVED   — sent immediately (succes-billede fra StoryBrand)
//   2. IN-PRODUCTION    — sent ~24 h after order
//   3. SHIPPED          — sent when the order actually ships (or on manual GET)
//
// All customer-facing copy is generated by Claude (masters: miller + sutherland),
// judged (brand + facts + compliance), logged as `pending_human` in
// dpn_interactions and (if PENDING_HUMAN_STRICT is not '1') dispatched through
// Postmark. When PENDING_HUMAN_STRICT=1 the mail goes to the human queue only
// and Michael pushes send from the queue UI (safe default until the voice is
// dialled in).
//
// Contract:
//   POST /api/agents/anna
//     body: raw Stripe event JSON (webhook)
//   POST /api/agents/anna?task=in_production   { order_id }
//   POST /api/agents/anna?task=shipped         { order_id, tracking_url }
//   GET  /api/agents/anna?task=cron_in_production
//                              → sweep orders 24h+ old, still 'received'
//   returns: { agent: 'anna', task, verdict, draft, details }
//
// Env: ANTHROPIC_API_KEY, SUPABASE_URL, SUPABASE_SERVICE_KEY, STRIPE_WEBHOOK_SECRET,
//      POSTMARK_TOKEN, POSTMARK_FROM, POSTMARK_REPLY_TO (all optional; missing
//      keys degrade to draft-only mode logged to the queue).

const crypto = require('crypto');
const { callClaude, loadVoiceRules, logAgentRun, buildAgentSystem, generateAndJudge } = require('./_shared');
const { composeMasters } = require('../masters/_index');
const { runJudges } = require('../judges');

// --- Personas & system prompt fragments -----------------------------------

const ROLE = `Du er "Anna" — DPN's Order-Concierge. Du skriver de tre kunde-mails der følger et køb:
1) ordre-modtaget, 2) i-produktion (24 t senere), 3) afsendt (med track-link).

Stemmen:
- Jenifer skriver til én kunde ad gangen. Personlig, rolig, editorial.
- Dansk brødtekst. Én kort engelsk tagline er ok, aldrig påklistret.
- Sentence case. Max ét ✦ eller emoji per mail. Aldrig udråbstegn-spam.
- Kunden er helten (StoryBrand): mail'en handler om DERES sæt, DERES fest, DERES hænder.
- Succes-billede: skriv scenen hvor kunden har sættet på — komplimenten ved bordet, følelsen.
- Aldrig sales-copy. Aldrig "køb mere". Ordren er allerede lagt — nu leverer vi den.
- Ingen løfter om leveringstider vi ikke ved — brug KUN datoer/tal fra facts-blokken.
- Signér som "Jenifer" (aldrig "DPN teamet" eller "med venlig hilsen").
- Ingen personlige data i mail-body ud over kundens fornavn og ordre-nummeret.`;

// --- Task-specific briefs -------------------------------------------------

const TASK_BRIEFS = {
  order_received: {
    kind: 'order_ack',
    subject_hint: (facts) => `Din ordre ${facts.order_number} er landet i atelieret ✦`,
    prompt: (facts) => `Kunden ${facts.first_name || 'kunden'} har lige lagt ordre ${facts.order_number}.
Indhold: ${facts.items_summary}.
Skriv en ordre-modtaget mail (150-220 ord) i Jenifer's stemme.

Mail skal indeholde, i denne rækkefølge:
1) En rolig åbningslinje der bekræfter at ordren er landet — ikke transaktionel.
2) Ét succes-billede: hvordan det føles at have sættet på (StoryBrand punkt 7).
3) Én sætning om at Jenifer maler i hånden — "one of a kind"-vinklen (Sutherland-reframe: "malet i atelieret over flere timer", ikke bare "håndmalet").
4) Hvad der sker næste: kunden hører fra os igen når sættet går i produktion, og igen når det afsendes.
5) Kort signatur: "— Jenifer".

Returnér KUN mail-body i markdown-lignende ren tekst (linjeskift ok, ingen H1/H2), uden emne-linje og uden meta-forklaring.`,
  },

  in_production: {
    kind: 'order_production',
    subject_hint: (facts) => `Dit sæt er nu under Jenifers pensel`,
    prompt: (facts) => `Kunde ${facts.first_name || 'kunden'} har ordre ${facts.order_number} som lige er gået i produktion.
Indhold: ${facts.items_summary}.

Skriv en "i produktion"-mail (120-180 ord) i Jenifer's stemme.

Mail skal indeholde:
1) Åbning: sættet er nu i atelieret og Jenifer er ved at male det.
2) Én sætning der viser processen konkret (basis, første lag, motiv-detail) — men uden at love et bestemt antal timer.
3) Sutherland-reframe: ingen "levering om X dage" — brug "du hører fra os igen når sættet er klar til fragt".
4) Én linje der styrker succes-billedet (kunden med sættet på til lejligheden).
5) Signatur "— Jenifer".

Returnér KUN mail-body ren tekst. Ingen emne-linje.`,
  },

  shipped: {
    kind: 'order_shipped',
    subject_hint: (facts) => `Dit sæt er på vej ✦ ordre ${facts.order_number}`,
    prompt: (facts) => `Kunde ${facts.first_name || 'kunden'} har ordre ${facts.order_number} som netop er afsendt.
Indhold: ${facts.items_summary}.
Track-link: ${facts.tracking_url || '(mangler — brug placeholder [TRACK])'}.

Skriv en "afsendt"-mail (100-150 ord) i Jenifer's stemme.

Mail skal indeholde:
1) Åbning: sættet forlod atelieret i dag.
2) En sætning der hylder detaljen (Sutherland-reframe: "malet over flere timer og pakket i hånden").
3) Direkte link til at følge pakken — som en almindelig sætning, IKKE en salesy CTA-knap.
4) Én kort linje om påsætning: "der ligger en lille guide i pakken" (aldrig "download app" el.lign.).
5) Succes-billede: "vi glæder os til at se dem på dig".
6) Signatur "— Jenifer".

Returnér KUN mail-body ren tekst. Ingen emne-linje. Brug track-link ordret som URL — ingen html.`,
  },
};

// --- Stripe webhook signature verification ---------------------------------
// Implements https://stripe.com/docs/webhooks/signatures without the SDK.

function verifyStripeSignature(rawBody, sigHeader, secret, toleranceSec = 300) {
  if (!sigHeader || !secret || !rawBody) return { ok: false, reason: 'missing_input' };
  const parts = sigHeader.split(',').reduce((acc, p) => {
    const [k, v] = p.split('=');
    if (k && v) (acc[k] = acc[k] || []).push(v);
    return acc;
  }, {});
  const tArr = parts.t;
  const v1Arr = parts.v1;
  if (!tArr || !v1Arr) return { ok: false, reason: 'malformed_header' };
  const t = tArr[0];
  const nowSec = Math.floor(Date.now() / 1000);
  if (Math.abs(nowSec - parseInt(t, 10)) > toleranceSec) {
    return { ok: false, reason: 'stale_timestamp' };
  }
  const payload = `${t}.${rawBody}`;
  const expected = crypto.createHmac('sha256', secret).update(payload, 'utf8').digest('hex');
  const match = v1Arr.some(v1 => {
    if (v1.length !== expected.length) return false;
    try { return crypto.timingSafeEqual(Buffer.from(v1), Buffer.from(expected)); } catch { return false; }
  });
  return { ok: match, reason: match ? 'ok' : 'signature_mismatch' };
}

// --- Supabase helpers (orders + queue lookup) ------------------------------

async function sbInsert(table, row) {
  const url = process.env.SUPABASE_URL, key = process.env.SUPABASE_SERVICE_KEY;
  if (!url || !key) return { ok: false, reason: 'no_supabase' };
  try {
    const r = await fetch(`${url}/rest/v1/${table}`, {
      method: 'POST',
      headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', Prefer: 'return=representation' },
      body: JSON.stringify(row),
    });
    const data = await r.json();
    if (!r.ok) return { ok: false, reason: `sb_${r.status}`, data };
    return { ok: true, data: Array.isArray(data) ? data[0] : data };
  } catch (e) {
    return { ok: false, reason: String(e) };
  }
}

async function sbUpdate(table, filter, patch) {
  const url = process.env.SUPABASE_URL, key = process.env.SUPABASE_SERVICE_KEY;
  if (!url || !key) return { ok: false, reason: 'no_supabase' };
  try {
    const r = await fetch(`${url}/rest/v1/${table}?${filter}`, {
      method: 'PATCH',
      headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', Prefer: 'return=representation' },
      body: JSON.stringify(patch),
    });
    const data = await r.json();
    if (!r.ok) return { ok: false, reason: `sb_${r.status}`, data };
    return { ok: true, data: Array.isArray(data) ? data[0] : data };
  } catch (e) {
    return { ok: false, reason: String(e) };
  }
}

async function sbSelect(table, query) {
  const url = process.env.SUPABASE_URL, key = process.env.SUPABASE_SERVICE_KEY;
  if (!url || !key) return { ok: false, reason: 'no_supabase', data: [] };
  try {
    const r = await fetch(`${url}/rest/v1/${table}?${query}`, {
      headers: { apikey: key, Authorization: `Bearer ${key}` },
    });
    const data = await r.json();
    if (!r.ok) return { ok: false, reason: `sb_${r.status}`, data: [] };
    return { ok: true, data: Array.isArray(data) ? data : [] };
  } catch (e) {
    return { ok: false, reason: String(e), data: [] };
  }
}

// --- Postmark dispatch (only used when PENDING_HUMAN_STRICT != '1') --------

async function sendPostmark({ to, subject, body }) {
  const token = process.env.POSTMARK_TOKEN || process.env.POSTMARK_SERVER_TOKEN;
  const from = process.env.POSTMARK_FROM;
  const replyTo = process.env.POSTMARK_REPLY_TO || from;
  if (!token || !from || !to) return { ok: false, reason: 'no_postmark_config' };
  try {
    const r = await fetch('https://api.postmarkapp.com/email', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-Postmark-Server-Token': token,
      },
      body: JSON.stringify({
        From: from,
        To: to,
        ReplyTo: replyTo,
        Subject: subject,
        TextBody: body,
        MessageStream: 'outbound',
      }),
    });
    const data = await r.json();
    if (!r.ok) return { ok: false, reason: `postmark_${r.status}`, data };
    return { ok: true, data };
  } catch (e) {
    return { ok: false, reason: String(e) };
  }
}

// --- Compose facts from a Stripe session -----------------------------------

function summarizeStripeSession(session) {
  const cd = session.customer_details || {};
  const first_name = (cd.name || '').split(' ')[0] || '';
  const email = cd.email || null;
  const order_number = (session.metadata && session.metadata.order_number)
    || (session.id ? session.id.slice(-8).toUpperCase() : `ORD-${Date.now().toString(36).slice(-6).toUpperCase()}`);

  // We don't expand line_items on the raw event; use display_items / metadata
  // if available. Otherwise generic phrase — the mail never quotes SKUs.
  const items_summary = (session.metadata && session.metadata.items_summary)
    || 'dit håndmalede DPN-sæt';

  return {
    first_name,
    email,
    order_number,
    items_summary,
    amount_total: session.amount_total || null,
    currency: (session.currency || 'dkk').toUpperCase(),
    stripe_session_id: session.id,
    tracking_url: (session.metadata && session.metadata.tracking_url) || null,
  };
}

// --- Core: draft, judge, log, (maybe) dispatch -----------------------------

async function draftJudgeLogDispatch({ task, facts, order_id, dispatch }) {
  const brief = TASK_BRIEFS[task];
  if (!brief) return { ok: false, reason: `unknown_task_${task}` };

  const voiceRules = await loadVoiceRules();
  const masters_block = composeMasters(['miller', 'sutherland']);
  const system = [
    ROLE,
    '',
    '# Strategiske linser (marketing-mestre du læner dig ind i)',
    masters_block,
    voiceRules,
  ].filter(Boolean).join('\n');

  const { text: draft, error } = await callClaude({
    system,
    messages: [{ role: 'user', content: brief.prompt(facts) }],
    max_tokens: 800,
  });

  if (!draft) {
    await logAgentRun({
      agent: 'anna', task, channel: 'email',
      ai_draft: '', final: '', verdict: 'block',
      note: `draft_failed order=${facts.order_number} err=${error || 'empty_draft'}`,
      judges: null,
    });
    return { ok: false, reason: 'draft_failed', error };
  }

  const judged = await runJudges({
    draft, kind: brief.kind, channel: 'email',
    facts: {
      order_number: facts.order_number,
      first_name: facts.first_name,
      items_summary: facts.items_summary,
      tracking_url: facts.tracking_url || null,
    },
  });

  const subject = brief.subject_hint(facts);
  const strict = process.env.PENDING_HUMAN_STRICT === '1';

  // Decide the verdict we store:
  //   block   → judge blocked, human must rewrite
  //   pending_human → judges passed but strict-mode or auto-approve-off
  //   auto    → judges passed AND strict is off AND dispatch succeeded
  let storedVerdict;
  let dispatchResult = null;
  if (judged.verdict === 'block') {
    storedVerdict = 'block';
  } else if (strict || !dispatch) {
    storedVerdict = 'pending_human';
  } else {
    dispatchResult = await sendPostmark({ to: facts.email, subject, body: draft });
    storedVerdict = dispatchResult.ok ? 'auto' : 'pending_human';
  }

  const noteMeta = {
    order_id: order_id || null,
    order_number: facts.order_number,
    subject,
    dispatch: dispatchResult,
  };

  await logAgentRun({
    agent: 'anna', task, channel: 'email',
    ai_draft: draft, final: draft,
    verdict: storedVerdict,
    note: `${JSON.stringify(noteMeta).slice(0, 400)}`,
    judges: judged.results,
  });

  // Also persist a row into dpn_order_emails so the sweep/cron can see
  // "already sent" per (order_id, task).
  if (order_id) {
    await sbInsert('dpn_order_emails', {
      order_id,
      task,
      subject,
      body_preview: draft.slice(0, 500),
      verdict: storedVerdict,
      dispatched_at: storedVerdict === 'auto' ? new Date().toISOString() : null,
    });
  }

  return {
    ok: true,
    task,
    verdict: storedVerdict,
    judge_verdict: judged.verdict,
    blocking_reasons: judged.blocking_reasons,
    subject,
    draft,
    dispatch: dispatchResult,
  };
}

// --- Entry points ----------------------------------------------------------

async function handleStripeWebhook(req) {
  // Vercel gives req.body already parsed for JSON. For signature verification
  // we need the raw string, which is available on req.rawBody in some
  // configurations. If missing, we degrade to accept-without-verify but log it.
  const rawBody = typeof req.body === 'string'
    ? req.body
    : (req.rawBody && Buffer.isBuffer(req.rawBody) ? req.rawBody.toString('utf8')
       : (req.rawBody ? String(req.rawBody) : JSON.stringify(req.body || {})));

  const secret = process.env.STRIPE_WEBHOOK_SECRET;
  const sig = req.headers['stripe-signature'];
  let sigResult = { ok: false, reason: 'not_verified' };
  if (secret) {
    sigResult = verifyStripeSignature(rawBody, sig, secret);
    if (!sigResult.ok) {
      return { status: 400, body: { agent: 'anna', task: 'webhook', error: 'invalid_signature', reason: sigResult.reason } };
    }
  }

  let event;
  try { event = typeof req.body === 'string' ? JSON.parse(req.body) : req.body; }
  catch (e) { return { status: 400, body: { agent: 'anna', task: 'webhook', error: 'bad_json' } }; }

  if (!event || event.type !== 'checkout.session.completed') {
    // Ack politely — Stripe retries on non-2xx
    return { status: 200, body: { agent: 'anna', task: 'webhook', ignored: event && event.type } };
  }

  const session = (event.data && event.data.object) || {};
  const facts = summarizeStripeSession(session);
  if (!facts.email) {
    return { status: 200, body: { agent: 'anna', task: 'webhook', error: 'no_customer_email', order_number: facts.order_number } };
  }

  // Persist the order (idempotent on stripe_session_id via UNIQUE).
  const orderInsert = await sbInsert('dpn_orders', {
    stripe_session_id: facts.stripe_session_id,
    order_number: facts.order_number,
    customer_email: facts.email,
    customer_first_name: facts.first_name,
    items_summary: facts.items_summary,
    amount_total: facts.amount_total,
    currency: facts.currency,
    status: 'received',
  });
  const order_id = orderInsert.ok && orderInsert.data && orderInsert.data.id
    ? orderInsert.data.id
    : null;
  const already_seen = !orderInsert.ok && orderInsert.data
    && (JSON.stringify(orderInsert.data).includes('duplicate') || JSON.stringify(orderInsert.data).includes('unique'));

  if (already_seen) {
    return { status: 200, body: { agent: 'anna', task: 'webhook', duplicate: true, order_number: facts.order_number } };
  }

  const result = await draftJudgeLogDispatch({
    task: 'order_received', facts, order_id, dispatch: true,
  });

  return {
    status: 200,
    body: {
      agent: 'anna',
      task: 'webhook',
      sig_verified: sigResult.ok,
      order_number: facts.order_number,
      order_id,
      email_result: result,
    },
  };
}

async function handleInProduction(req) {
  const body = typeof req.body === 'string' ? JSON.parse(req.body || '{}') : (req.body || {});
  const order_id = body.order_id;
  if (!order_id) return { status: 400, body: { agent: 'anna', task: 'in_production', error: 'order_id required' } };

  const orders = await sbSelect('dpn_orders', `id=eq.${encodeURIComponent(order_id)}&limit=1`);
  const o = (orders.data || [])[0];
  if (!o) return { status: 404, body: { agent: 'anna', task: 'in_production', error: 'order_not_found' } };

  const facts = {
    first_name: o.customer_first_name || '',
    email: o.customer_email,
    order_number: o.order_number,
    items_summary: o.items_summary || 'dit håndmalede DPN-sæt',
    tracking_url: null,
  };
  const result = await draftJudgeLogDispatch({
    task: 'in_production', facts, order_id, dispatch: true,
  });

  if (result.ok && result.verdict !== 'block') {
    await sbUpdate('dpn_orders', `id=eq.${encodeURIComponent(order_id)}`, {
      status: 'in_production',
      in_production_at: new Date().toISOString(),
    });
  }
  return { status: 200, body: { agent: 'anna', task: 'in_production', ...result } };
}

async function handleShipped(req) {
  const body = typeof req.body === 'string' ? JSON.parse(req.body || '{}') : (req.body || {});
  const order_id = body.order_id;
  const tracking_url = body.tracking_url || '';
  if (!order_id) return { status: 400, body: { agent: 'anna', task: 'shipped', error: 'order_id required' } };
  if (!tracking_url) return { status: 400, body: { agent: 'anna', task: 'shipped', error: 'tracking_url required' } };

  const orders = await sbSelect('dpn_orders', `id=eq.${encodeURIComponent(order_id)}&limit=1`);
  const o = (orders.data || [])[0];
  if (!o) return { status: 404, body: { agent: 'anna', task: 'shipped', error: 'order_not_found' } };

  const facts = {
    first_name: o.customer_first_name || '',
    email: o.customer_email,
    order_number: o.order_number,
    items_summary: o.items_summary || 'dit håndmalede DPN-sæt',
    tracking_url,
  };
  const result = await draftJudgeLogDispatch({
    task: 'shipped', facts, order_id, dispatch: true,
  });

  if (result.ok && result.verdict !== 'block') {
    await sbUpdate('dpn_orders', `id=eq.${encodeURIComponent(order_id)}`, {
      status: 'shipped',
      shipped_at: new Date().toISOString(),
      tracking_url,
    });
  }
  return { status: 200, body: { agent: 'anna', task: 'shipped', ...result } };
}

// GET /api/agents/anna?task=cron_in_production
// Sweeps orders that are still 'received' and >= 24 h old and fires the
// in-production email once per order.
async function handleCronInProduction() {
  const cutoff = new Date(Date.now() - 24 * 3600 * 1000).toISOString();
  const orders = await sbSelect(
    'dpn_orders',
    `status=eq.received&created_at=lte.${encodeURIComponent(cutoff)}&order=created_at.asc&limit=25`
  );
  const list = orders.data || [];
  const results = [];
  for (const o of list) {
    // Guard: skip if an in_production email already exists.
    const existing = await sbSelect(
      'dpn_order_emails',
      `order_id=eq.${encodeURIComponent(o.id)}&task=eq.in_production&limit=1`
    );
    if ((existing.data || []).length > 0) {
      results.push({ order_id: o.id, skipped: 'already_emailed' });
      continue;
    }
    const facts = {
      first_name: o.customer_first_name || '',
      email: o.customer_email,
      order_number: o.order_number,
      items_summary: o.items_summary || 'dit håndmalede DPN-sæt',
      tracking_url: null,
    };
    const r = await draftJudgeLogDispatch({
      task: 'in_production', facts, order_id: o.id, dispatch: true,
    });
    if (r.ok && r.verdict !== 'block') {
      await sbUpdate('dpn_orders', `id=eq.${encodeURIComponent(o.id)}`, {
        status: 'in_production',
        in_production_at: new Date().toISOString(),
      });
    }
    results.push({ order_id: o.id, order_number: o.order_number, verdict: r.verdict, judge_verdict: r.judge_verdict });
  }
  return { status: 200, body: { agent: 'anna', task: 'cron_in_production', swept: list.length, results } };
}

// --- Main handler ----------------------------------------------------------

module.exports = async (req, res) => {
  const query = req.query || {};
  const task = (query.task || '').toString();
  const isCron = req.headers['x-vercel-cron'] === '1';

  try {
    let out;
    if (req.method === 'POST' && !task) {
      // Stripe webhook path
      out = await handleStripeWebhook(req);
    } else if (req.method === 'POST' && task === 'in_production') {
      out = await handleInProduction(req);
    } else if (req.method === 'POST' && task === 'shipped') {
      out = await handleShipped(req);
    } else if ((req.method === 'GET' || isCron) && task === 'cron_in_production') {
      out = await handleCronInProduction();
    } else {
      out = { status: 405, body: { agent: 'anna', error: 'Unsupported method/task', method: req.method, task } };
    }
    return res.status(out.status).json(out.body);
  } catch (e) {
    // Best-effort log; NEVER crash the webhook (Stripe would retry infinitely).
    await logAgentRun({
      agent: 'anna', task: task || 'webhook', channel: 'system',
      ai_draft: '', final: '', verdict: 'block',
      note: `unhandled_error: ${String(e).slice(0, 400)}`,
      judges: null,
    });
    return res.status(200).json({ agent: 'anna', task: task || 'webhook', error: 'unhandled', message: String(e).slice(0, 200) });
  }
};

// Export helpers so future tests (or an `anna:in_production` cron sibling) can
// re-use the same draft/judge pipeline without importing the HTTP layer.
module.exports.draftJudgeLogDispatch = draftJudgeLogDispatch;
module.exports.summarizeStripeSession = summarizeStripeSession;
module.exports.verifyStripeSignature = verifyStripeSignature;
module.exports.TASK_BRIEFS = TASK_BRIEFS;
